# Generated by Django 3.2.20 on 2023-07-11 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='table',
            name='seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='table',
            name='category',
            field=models.CharField(choices=[('B', 'BAR'), ('D', 'DINING')], max_length=30),
        ),
        migrations.DeleteModel(
            name='TableCategory',
        ),
    ]
