# Generated by Django 3.2.20 on 2023-07-11 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20230711_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='category',
            field=models.CharField(choices=[('B', 'BAR'), ('D', 'DINING')], max_length=1),
        ),
    ]
