# Generated by Django 3.2.20 on 2023-07-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_table_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='category',
            field=models.CharField(choices=[('Table1', 'BAR'), ('Table2', 'BAR'), ('Table3', 'BAR'), ('Table4', 'BAR'), ('Table5', 'DINING'), ('Table6', 'DINING'), ('Table7', 'DINING')], max_length=6),
        ),
    ]
