# Generated by Django 3.2.20 on 2023-07-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_alter_table_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='category',
            field=models.CharField(choices=[('BT3', 'Table for 3 people'), ('BT4', 'Table for 4 people'), ('BT6', 'Table for 6 people'), ('BT5', 'Table for 5 people'), ('DT2', 'Table for 2 people'), ('DT4', 'Table for 4 people'), ('DT6', 'Table for 6 people')], max_length=3),
        ),
    ]
