# Generated by Django 3.2.20 on 2023-07-18 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_alter_table_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='category',
            field=models.CharField(choices=[('A', 'Table for 3 people'), ('B', 'Table for 4 people'), ('C', 'Table for 6 people'), ('D', 'Table for 5 people'), ('E', 'Table for 2 people'), ('F', 'Table for 4 people'), ('G', 'Table for 6 people')], max_length=1),
        ),
    ]
